language: go

install: echo "Do not install go dependencies" > /dev/null 2>&1

script:
  - go vet
  - test -z "$(go list ./... | grep -v vendor | xargs go fmt)"

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash

